// Copyright (C) 2026  aSocial Developers
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Author: Rabit (@rabits)

#include "asocial_protogen/templates.h"

namespace asocial_protogen {

const char* commonHeaderTemplate()
{
    return R"TPL(// Code generated by protoc-gen-coredb. DO NOT EDIT.
//
// Source: aSocial protobuf definitions
// Generator: libs/asocial_proto/libs/asocial_protogen

#pragma once

// Qt-generated well-known type (do not mix with <google/protobuf/timestamp.pb.h>).
#include <QtProtobufWellKnownTypes/google/protobuf/timestamp.qpb.h>

#include <QDateTime>
#include <QFlags>
#include <QList>
#include <QString>
#include <QStringList>
#include <QUuid>

#include <functional>

namespace asocial::v1::db {

// ============================================================
// Timestamp Helpers
// ============================================================

inline google::protobuf::Timestamp toTimestamp(const QDateTime& dt)
{
    google::protobuf::Timestamp ts;
    ts.setSeconds(dt.toSecsSinceEpoch());
    ts.setNanos(dt.time().msec() * 1000000);
    return ts;
}

inline QDateTime fromTimestamp(const google::protobuf::Timestamp& ts)
{
    return QDateTime::fromMSecsSinceEpoch(ts.seconds() * 1000 + ts.nanos() / 1000000);
}

inline qint64 timestampToMsEpoch(const google::protobuf::Timestamp& ts)
{
    return ts.seconds() * 1000 + ts.nanos() / 1000000;
}

// ISO 8601 format "yyyy-MM-ddTHH:mm:ss" in UTC for use in database keys.
// Enables lexicographic filtering by date/time.
inline QString timestampToIso(const google::protobuf::Timestamp& ts)
{
    return fromTimestamp(ts).toString(Qt::ISODate);
}

inline QString timestampToIsoKey(const google::protobuf::Timestamp& ts)
{
    return fromTimestamp(ts).toUTC().toString(QStringLiteral("yyyy-MM-ddTHH:mm:ss"));
}

inline QString newId()
{
    return QUuid::createUuid().toString(QUuid::WithoutBraces);
}

// ============================================================
// Validation (shared types)
// ============================================================

class ValidationError {
public:
    QString field;
    QString message;

    ValidationError() = default;
    ValidationError(QString f, QString m)
        : field(std::move(f)), message(std::move(m))
    {
    }
};

class ForeignKeyRef {
public:
    QString field;
    QString targetEntity;
    QString targetField;
    QString lookupKeyPrefix;
    QString value;

    ForeignKeyRef() = default;
    ForeignKeyRef(QString field, QString targetEntity, QString targetField,
                  QString lookupKeyPrefix, QString value)
        : field(std::move(field)), targetEntity(std::move(targetEntity)),
          targetField(std::move(targetField)), lookupKeyPrefix(std::move(lookupKeyPrefix)),
          value(std::move(value))
    {
    }
};

class ValidationResult {
public:
    bool valid = true;
    QList<ValidationError> errors;
    QList<ForeignKeyRef> foreignKeys;

    void addError(const QString& f, const QString& m);
    void addFK(const QString& f, const QString& te, const QString& tf,
               const QString& kp, const QString& v);
    QString toString() const;
};

using KeyExistsFn = std::function<bool(const QString&)>;

// ============================================================
// Access Permission System
// ============================================================

enum class AccessCategory : quint32 {
    None           = 0,
    ProfileRead    = 1 << 0,
    ProfileWrite   = 1 << 1,
    DataRead       = 1 << 2,
    DataWrite      = 1 << 3,
    SettingsRead   = 1 << 4,
    SettingsWrite  = 1 << 5,
    ContainerRead  = 1 << 6,
    ContainerWrite = 1 << 7,
    AppLifecycle   = 1 << 8,
    ExportImport   = 1 << 9,
    PluginAccess   = 1 << 10,
};

Q_DECLARE_FLAGS(AccessPermissions, AccessCategory)

AccessPermissions expandPermissions(AccessPermissions p);
QStringList permissionNames(AccessPermissions p);

} // namespace asocial::v1::db

Q_DECLARE_OPERATORS_FOR_FLAGS(asocial::v1::db::AccessPermissions)
)TPL";
}

const char* commonSourceTemplate()
{
    return R"TPL(// Code generated by protoc-gen-coredb. DO NOT EDIT.
//
// Source: aSocial protobuf definitions
// Generator: libs/asocial_proto/libs/asocial_protogen

#include "{{ common_include_path }}"

namespace asocial::v1::db {

void ValidationResult::addError(const QString& f, const QString& m)
{
    valid = false;
    errors.append(ValidationError(f, m));
}

void ValidationResult::addFK(const QString& f, const QString& te, const QString& tf,
                             const QString& kp, const QString& v)
{
    foreignKeys.append(ForeignKeyRef(f, te, tf, kp, v));
}

QString ValidationResult::toString() const
{
    QStringList parts;
    for( const auto& e : errors )
        parts << e.field + QStringLiteral(": ") + e.message;
    return parts.join(QStringLiteral("; "));
}

AccessPermissions expandPermissions(AccessPermissions p)
{
    if( p.testFlag(AccessCategory::ProfileWrite) )
        p |= AccessCategory::ProfileRead;
    if( p.testFlag(AccessCategory::DataWrite) )
        p |= AccessCategory::DataRead;
    if( p.testFlag(AccessCategory::SettingsWrite) )
        p |= AccessCategory::SettingsRead;
    if( p.testFlag(AccessCategory::ContainerWrite) )
        p |= AccessCategory::ContainerRead;
    return p;
}

QStringList permissionNames(AccessPermissions p)
{
    QStringList n;
    if( p.testFlag(AccessCategory::ProfileRead) )    n << QStringLiteral("ProfileRead");
    if( p.testFlag(AccessCategory::ProfileWrite) )   n << QStringLiteral("ProfileWrite");
    if( p.testFlag(AccessCategory::DataRead) )       n << QStringLiteral("DataRead");
    if( p.testFlag(AccessCategory::DataWrite) )      n << QStringLiteral("DataWrite");
    if( p.testFlag(AccessCategory::SettingsRead) )   n << QStringLiteral("SettingsRead");
    if( p.testFlag(AccessCategory::SettingsWrite) )  n << QStringLiteral("SettingsWrite");
    if( p.testFlag(AccessCategory::ContainerRead) )    n << QStringLiteral("ContainerRead");
    if( p.testFlag(AccessCategory::ContainerWrite) )  n << QStringLiteral("ContainerWrite");
    if( p.testFlag(AccessCategory::AppLifecycle) )   n << QStringLiteral("AppLifecycle");
    if( p.testFlag(AccessCategory::ExportImport) )   n << QStringLiteral("ExportImport");
    if( p.testFlag(AccessCategory::PluginAccess) )   n << QStringLiteral("PluginAccess");
    if( n.isEmpty() ) n << QStringLiteral("None");
    return n;
}

} // namespace asocial::v1::db
)TPL";
}

const char* entityHeaderTemplate()
{
    return R"TPL(// Code generated by protoc-gen-coredb. DO NOT EDIT.
//
// Source: aSocial protobuf definitions
// Generator: libs/asocial_proto/libs/asocial_protogen

#pragma once

#include "{{ common_include_path }}"
#include "{{ qpb_include_path }}"

namespace asocial::v1::db {

// ============================================================
// KV Key Helpers (declarations)
// ============================================================

namespace keys {
{% for e in entities %}
{% if e.singleton %}
QString {{ e.fn_name }}();
{% else %}
QString {{ e.fn_name }}({{ e.key_fn_params }});
{% for po in e.prefix_overloads %}
{% if po.param_count == 0 %}
QString {{ e.fn_name }}_prefix();
{% else %}
QString {{ e.fn_name }}_prefix({{ po.params }});
{% endif %}
{% endfor %}
{% endif %}
{% endfor %}
} // namespace keys

// ============================================================
// Validation (declarations)
// ============================================================
{% for e in entities %}
ValidationResult validate{{ e.name }}(const {{ e.cpp_type }}& obj);
ValidationResult validate{{ e.name }}Full(const {{ e.cpp_type }}& obj, KeyExistsFn exists);
{% endfor %}

// ============================================================
// Factory Functions (declarations)
// ============================================================
{% for e in entities %}
{% if not e.singleton %}
{{ e.cpp_type }} create{{ e.name }}();
{% endif %}
{% endfor %}

} // namespace asocial::v1::db
)TPL";
}

const char* entitySourceTemplate()
{
    return R"TPL(// Code generated by protoc-gen-coredb. DO NOT EDIT.
//
// Source: aSocial protobuf definitions
// Generator: libs/asocial_proto/libs/asocial_protogen

#include "{{ header_include_path }}"

namespace asocial::v1::db {

// ============================================================
// KV Key Helpers (implementations)
// ============================================================

namespace keys {
{% for e in entities %}
{% if e.singleton %}
static const QString {{ e.const_name }} = QStringLiteral("{{ e.key_prefix }}");

QString {{ e.fn_name }}()
{
    return {{ e.const_name }};
}

{% else %}
static const QString {{ e.const_name }}_PFX = QStringLiteral("{{ e.key_prefix }}/");

QString {{ e.fn_name }}({{ e.key_fn_params }})
{
    return {{ e.const_name }}_PFX + {{ e.key_fn_body }};
}

{% for po in e.prefix_overloads %}
{% if po.param_count == 0 %}
QString {{ e.fn_name }}_prefix()
{
    {{ po.body }};
}

{% else %}
QString {{ e.fn_name }}_prefix({{ po.params }})
{
    {{ po.body }};
}

{% endif %}
{% endfor %}
{% endif %}
{% endfor %}
} // namespace keys

// ============================================================
// Validation
// ============================================================
{% for e in entities %}
ValidationResult validate{{ e.name }}(const {{ e.cpp_type }}& obj)
{
    ValidationResult r;
{% for f in e.required_fields %}
    if( obj.{{ f.getter }}().isEmpty() )
        r.addError(QStringLiteral("{{ f.proto_name }}"), QStringLiteral("{{ f.proto_name }} is required"));
{% endfor %}
{% for f in e.fk_fields %}
{% for fk in f.fk_targets %}
    if( !obj.{{ f.getter }}().isEmpty() )
        r.addFK(QStringLiteral("{{ f.proto_name }}"), QStringLiteral("{{ fk.entity }}"),
                QStringLiteral("{{ fk.field }}"), QStringLiteral("{{ fk.key_prefix }}/"),
                obj.{{ f.getter }}());
{% endfor %}
{% endfor %}
    return r;
}

ValidationResult validate{{ e.name }}Full(const {{ e.cpp_type }}& obj, KeyExistsFn exists)
{
    auto r = validate{{ e.name }}(obj);
    if( exists ) {
        for( const auto& fk : r.foreignKeys ) {
            if( !fk.value.isEmpty() && !exists(fk.lookupKeyPrefix + fk.value) )
                r.addError(fk.field, fk.targetEntity + QStringLiteral(" not found: ") + fk.value);
        }
    }
    return r;
}

{% endfor %}
// ============================================================
// Factory Functions
// ============================================================
{% for e in entities %}
{% if not e.singleton %}
{{ e.cpp_type }} create{{ e.name }}()
{
    {{ e.cpp_type }} obj;
    const auto now = toTimestamp(QDateTime::currentDateTimeUtc());
{% if e.has_uid %}
    obj.setUid(newId());
{% endif %}
{% if e.has_created_at %}
    obj.setCreatedAt(now);
{% endif %}
{% if e.has_updated_at %}
    obj.setUpdatedAt(now);
{% endif %}
    return obj;
}

{% endif %}
{% endfor %}
} // namespace asocial::v1::db
)TPL";
}

const char* coredbAggregatorHeaderTemplate()
{
    return R"TPL(// Code generated by protoc-gen-coredb. DO NOT EDIT.
//
// Source: aSocial protobuf definitions
// Generator: libs/asocial_proto/libs/asocial_protogen
//
// Umbrella include: pulls shared helpers plus every per-.proto coredb header.

#pragma once

#include "{{ common_include_path }}"
{% for inc in type_includes %}
#include "{{ inc }}"
{% endfor %}
)TPL";
}

const char* coredbAggregatorSourceTemplate()
{
    return R"TPL(// Code generated by protoc-gen-coredb. DO NOT EDIT.
//
// Umbrella translation unit — implementations live in common.proto.gen.cpp
// and per-type *.proto.gen.cpp files.

#include "{{ coredb_header_include_path }}"
)TPL";
}

} // namespace asocial_protogen
