// Copyright (C) 2026  aSocial Developers
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Author: Rabit (@rabits)

#ifndef CORE_H
#define CORE_H

#include "CoreInterface.h"
#include "plugin/DBKVPluginInterface.h"
#include "plugin/VFS/VFSContainerPluginInterface.h"
#include "plugin/VFSPluginInterface.h"

#include <QObject>

class QCoreApplication;

namespace db = asocial::v1::db;

/**
 * @brief Application-wide singleton managing the plugin chain and profile lifecycle.
 *
 * Storage pipeline:
 *   VFS-cake container (data.vfs)  ->  DBKV-rocksdb (protobuf KV store)
 *
 * KV key scheme, validation, and factory functions are auto-generated by
 * protoc-gen-coredb from proto annotations into asocial/v1/coredb.gen.h.
 * This class uses db::keys::*, db::validate*, db::create* helpers
 * to implement the CRUD operations defined in CoreInterface.
 */
class Core : public QObject, public CoreInterface
{
    Q_OBJECT
    Q_INTERFACES(CoreInterface)

public:
    inline static Core* I()
    {
        if( s_pInstance == nullptr )
            s_pInstance = new Core();
        return s_pInstance;
    }
    inline static void destroyI() { delete s_pInstance; }

    // ---- Plugin wiring (called from main) --------------------------------
    void setDBKVPlugin(const QString& pluginName);
    void setDBKVProfilePlugin(const QString& pluginName);
    void setVFSPlugin(const QString& pluginName);
    void setApp(QCoreApplication* app);

    // ---- CoreInterface implementation ------------------------------------

    DBKVPluginInterface* getDBKV() const override;
    DBKVPluginInterface* getDBKVProfile() const override;
    VFSPluginInterface* getVFS() const override;

    bool createContainer(const QString& path, quint64 maxSizeBytes = 0) override;
    bool isContainerInitialized() const override;
    QString containerPath() const override;

    bool openProfile(const QString& password) override;
    bool createProfile(const QString& password, const QString& displayName) override;
    void closeProfile() override;
    bool isProfileOpen() const override;
    bool deleteCurrentProfile(std::function<void(int)> progress = nullptr) override;

    QByteArray exportProfile(const QString& encryptionPassword = QString()) override;
    bool importProfile(const QByteArray& data, const QString& decryptionPassword, const QString& vfsPassword) override;

    QVariant getSetting(const QString& key) const override;
    bool setSetting(const QString& key, const QVariant& value) override;
    QStringList listSettings() const override;

    asocial::v1::Profile getProfile() const override;
    bool storeProfile(const asocial::v1::Profile& profile) override;
    QString getCurrentProfileId() const override;
    QString currentPersonaName() const override;

    QList<asocial::v1::ProfileParameter> listParams() const override;
    asocial::v1::ProfileParameter createParam(const QString& paramKey) override;
    asocial::v1::ProfileParameter getParam(const QString& paramKey) const override;
    bool storeParam(const asocial::v1::ProfileParameter& param) override;
    bool deleteParam(const QString& paramKey) override;

    bool setActivePersona(const QString& personaId) override;
    QString activePersonaId() const override;

    QList<asocial::v1::Persona> listPersonas() const override;
    asocial::v1::Persona createPersona(const QString& displayName) override;
    asocial::v1::Persona getPersona(const QString& personaId) const override;
    bool storePersona(const asocial::v1::Persona& persona) override;
    bool deletePersona(const QString& personaId) override;

    QList<asocial::v1::Contact> listContacts() const override;
    asocial::v1::Contact createContact(const QString& displayName) override;
    asocial::v1::Contact getContact(const QString& contactId) const override;
    bool storeContact(const asocial::v1::Contact& contact) override;
    bool deleteContact(const QString& contactId) override;
    QList<asocial::v1::Contact> searchContacts(const QString& query) const override;

    QList<asocial::v1::Group> listGroups() const override;
    asocial::v1::Group createGroup(const QString& name) override;
    asocial::v1::Group getGroup(const QString& groupId) const override;
    bool storeGroup(const asocial::v1::Group& group) override;
    bool deleteGroup(const QString& groupId) override;
    bool addGroupMember(const QString& groupId, const QString& contactId) override;
    bool removeGroupMember(const QString& groupId, const QString& contactId) override;
    QList<asocial::v1::GroupMember> listGroupMembers(const QString& groupId) const override;

    QList<asocial::v1::Message> listMessages(int limit = 50) const override;
    asocial::v1::Message createMessage(
        const QString& recipientId, const QString& body, const QString& recipientType) override;
    asocial::v1::Message getMessage(const QString& messageId) const override;
    bool storeMessage(const asocial::v1::Message& message) override;
    bool deleteMessage(const QString& messageId) override;

    QList<asocial::v1::Event> listEvents() const override;
    asocial::v1::Event createEvent(const QString& title, const QString& date) override;
    asocial::v1::Event getEvent(const QString& eventId) const override;
    bool storeEvent(const asocial::v1::Event& event) override;
    bool deleteEvent(const QString& eventId) override;

    void exit() override;

    void init();

signals:
    void profileChanged() override;

private:
    explicit Core(QObject* parent = nullptr);
    ~Core() override;

    QString dbFileName() const;
    static void secureWipe(QByteArray& buf);
    void flushProfile();

    /** @brief Check whether a key exists in the profile DB (for FK validation). */
    bool keyExists(const QString& key) const;

    static Core* s_pInstance;

    QCoreApplication* m_app = nullptr;

    DBKVPluginInterface* m_dbkv = nullptr;
    DBKVPluginInterface* m_dbkvProfile = nullptr;
    VFSPluginInterface* m_vfs = nullptr;

    VFSContainerPluginInterface* m_container = nullptr;
    QIODevice* m_dbDevice = nullptr;

    QString m_containerPath;
    QString m_currentProfileId;
    QString m_activePersonaId;
};

#endif // CORE_H
